apiVersion: 1

datasources:
  - name: HS InfluxDB Flux
    uid: hs_influxdb_flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: true
    jsonData:
      version: Flux
      organization: home-services
      defaultBucket: home-services
    secureJsonData:
      token: dev-influx-token

  - name: HS InfluxDB InfluxQL
    uid: hs_influxdb_influxql
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: true
    jsonData:
      version: InfluxQL
      dbName: home-services
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token dev-influx-token
